# Google Cloud Build configuration for building CUDA and CPU Docker images

steps:
  # Build CUDA (NVIDIA GPU) image with both SHA and latest tags
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-cuda'
    args:
      - 'build'
      - '--tag'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-${SHORT_SHA}'
      - '--tag'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-latest'
      - '--file'
      - 'Dockerfile.cuda'
      - '.'
    timeout: '3600s'

  # Build CPU-only image with both SHA and latest tags
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-cpu'
    args:
      - 'build'
      - '--tag'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cpu-${SHORT_SHA}'
      - '--tag'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cpu-latest'
      - '--file'
      - 'Dockerfile.cpu'
      - '.'
    timeout: '3600s'

# Substitution variables
substitutions:
  _GCR_REGION: 'us-east1'
  _GCR_REPOSITORY: 'cv-mm-images'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build
timeout: '7200s'

# Cloud Build will automatically push these images after the build completes
images:
  - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-${SHORT_SHA}'
  - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-latest'
  - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cpu-${SHORT_SHA}'
  - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cpu-latest'
