# Google Cloud Build configuration for building CUDA Docker image only

steps:
  # Build CUDA (NVIDIA GPU) image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-cuda'
    args:
      - 'build'
      - '--tag'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-${SHORT_SHA}'
      - '--tag'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-latest'
      - '--file'
      - 'Dockerfile.cuda'
      - '.'
    timeout: '3600s'

  # Push CUDA image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-cuda'
    args:
      - 'push'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-${SHORT_SHA}'
    waitFor: ['build-cuda']

  # Push CUDA image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-cuda-latest'
    args:
      - 'push'
      - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-latest'
    waitFor: ['build-cuda']

# Substitution variables
substitutions:
  _GCR_REGION: 'us-central1'
  _GCR_REPOSITORY: 'cv-mm-images'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build
timeout: '7200s'

# Images to be pushed to registry
images:
  - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-${SHORT_SHA}'
  - '${_GCR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GCR_REPOSITORY}/cv-mm:cuda-latest'
